# Generated by Django 4.2.6 on 2023-10-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0014_alter_applications_aply_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='phonenumber',
            field=models.CharField(default='9446362021', max_length=10),
        ),
        migrations.AlterField(
            model_name='applications',
            name='pincode',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
